### ISSUE TITLE
AttributeError: Can't pickle local object 'build_transforms.<locals>.apply_transforms'

### ISSUE THREAD

**Issue by yu9s** [Chain-Mao/WiFi-Person-ReID#1]
Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "./fastreid/engine/launch.py", line 64, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "./fastreid/engine/launch.py", line 103, in _distributed_worker
    main_func(*args)
  File "/home/jovyan/sunshiru/REID1/WiFi-Person-ReID/tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "./fastreid/engine/defaults.py", line 215, in __init__
    self._trainer = (AMPTrainer if cfg.SOLVER.AMP.ENABLED else SimpleTrainer)(
  File "./fastreid/engine/train_loop.py", line 322, in __init__
    super().__init__(model, data_loader, optimizer, param_wrapper)
  File "./fastreid/engine/train_loop.py", line 221, in __init__
    self._data_loader_iter = iter(data_loader)
  File "./fastreid/data/data_utils.py", line 157, in __iter__
    self.iter = super().__iter__()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/conda/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'build_transforms.<locals>.apply_transforms'

Thank you for your work, When I run projects, the error is reported.
is there anything wrong with me?? please!!

**Comment by Chain-Mao** [comment]
> Traceback (most recent call last): File "tools/train_net.py", line 51, in launch( File "./fastreid/engine/launch.py", line 64, in launch mp.spawn( File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn return start_processes(fn, args, nprocs, join, daemon, start_method='spawn') File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes while not context.join(): File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join raise Exception(msg) Exception:
> 
> -- Process 0 terminated with the following error: Traceback (most recent call last): File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap fn(i, *args) File "./fastreid/engine/launch.py", line 103, in _distributed_worker main_func(*args) File "/home/jovyan/sunshiru/REID1/WiFi-Person-ReID/tools/train_net.py", line 42, in main trainer = DefaultTrainer(cfg) File "./fastreid/engine/defaults.py", line 215, in **init** self._trainer = (AMPTrainer if cfg.SOLVER.AMP.ENABLED else SimpleTrainer)( File "./fastreid/engine/train_loop.py", line 322, in **init** super().**init**(model, data_loader, optimizer, param_wrapper) File "./fastreid/engine/train_loop.py", line 221, in **init** self._data_loader_iter = iter(data_loader) File "./fastreid/data/data_utils.py", line 157, in **iter** self.iter = super().**iter**() File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 352, in **iter** return self._get_iterator() File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 801, in **init** w.start() File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 121, in start self._popen = self._Popen(self) File "/opt/conda/lib/python3.8/multiprocessing/context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "/opt/conda/lib/python3.8/multiprocessing/context.py", line 283, in _Popen return Popen(process_obj) File "/opt/conda/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in **init** super().**init**(process_obj) File "/opt/conda/lib/python3.8/multiprocessing/popen_fork.py", line 19, in **init** self._launch(process_obj) File "/opt/conda/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch reduction.dump(process_obj, fp) File "/opt/conda/lib/python3.8/multiprocessing/reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) AttributeError: Can't pickle local object 'build_transforms..apply_transforms'
> 
> Thank you for your work, When I run projects, the error is reported. is there anything wrong with me?? please!!

Oh, Sorry, I haven't sorted out this code yet, but you can modify the code yourself to make it work. My code was modified on fastreid. You can first run through the fast-reid code and make modifications based on it. The overall structure is in modeling/meta_arch/baseline.py, the wifi model is in modeling/backbones/wibert.py, and the loss function is in modeling/losses/triplet_loss.py and soft_triple. You can add or modify these codes in fastreid.
